const courses = {
  aviation: [], // existing aviation code omitted for brevity
  biology: [
    { question: "Science relies on what to test natural explanations?", options: ["Speculative ideas","Observations","Beliefs","Authority"], answer: 1 },
    { question: "A hypothesis is best defined as:", options: ["A comprehensive explanation","A proven fact","A testable statement","A random guess"], answer: 2 },
    { question: "A scientific theory is:", options: ["A proven fact","An untested idea","A comprehensive explanation supported by evidence","A single experiment result"], answer: 2 },
    { question: "In science, evidence refers to:", options: ["Opinions of experts","Observations","Unvalidated claims","Popular belief"], answer: 1 },
    { question: "The scientific method requires:", options: ["Emotional reasoning","Testable predictions","Unquestioned assumptions","A single experiment"], answer: 1 },
    { question: "Fact in science is a hypothesis that has been:", options: ["Disproven","Ignored","Provisionally accepted","Randomly chosen"], answer: 2 },
    { question: "Theory differs from fact as it provides:", options: ["Experimental error","Explanatory power","Certainty","None of the above"], answer: 1 },
    { question: "Elements are substances that cannot be further broken down by chemical means.", options: ["True","False"], answer: 0 },
    { question: "Atomic number equals the number of protons in an atom.", options: ["True","False"], answer: 0 },
    { question: "Valence shell can hold up to how many electrons?", options: ["2","8","18","32"], answer: 1 },
    { question: "A covalent bond involves:", options: ["Transfer of electrons","Sharing of electrons","Complete loss of electrons","Magnetic attraction"], answer: 1 },
    { question: "An ionic bond involves:", options: ["Sharing of electrons","Transfer of electrons","No electron interaction","Electron tunneling"], answer: 1 },
    { question: "Water is polar because:", options: ["Hydrogen is more electronegative","Oxygen is more electronegative","It has no charge","It is nonpolar"], answer: 1 },
    { question: "pH 7 is considered:", options: ["Acidic","Neutral","Basic","Salt"], answer: 1 },
    { question: "Higher pH indicates lower hydrogen ion concentration.", options: ["True","False"], answer: 0 },
    { question: "Prokaryotes lack a true nucleus.", options: ["True","False"], answer: 0 },
    { question: "Prokaryotic ribosomes are:", options: ["Membrane-bound","Free-floating","Absent","Only in nucleus"], answer: 1 },
    { question: "Cell wall function is to:", options: ["Generate ATP","Provide shape and prevent bursting","Store DNA","Transmit signals"], answer: 1 },
    { question: "Flagella in bacteria:", options: ["Whip like eukaryotes","Rotate to provide motility","Are for photosynthesis","Are not present"], answer: 1 },
    { question: "Plasmids are:", options: ["Membrane proteins","Ribosomes","Extra-chromosomal DNA","Lipid droplets"], answer: 2 },
    { question: "What is the definition of science?", options: ["A system of beliefs","A body of knowledge obtained and tested through the scientific method","The study of living organisms only","The pursuit of absolute truth"], answer: 1 },
    { question: "In science, what is a comprehensive explanation of some aspect of nature supported by a vast body of evidence?", options: ["A hypothesis","A fact","A theory","An observation"], answer: 2 },
    { question: "What is the smallest unit of an element that retains all of that element's properties?", options: ["A molecule","An atom","A proton","An electron"], answer: 1 },
    { question: "Atoms with the same number of protons but different numbers of neutrons are called:", options: ["Ions","Elements","Isotopes","Molecules"], answer: 2 },
    { question: "The outermost electron shell of an atom is called the:", options: ["Nucleus","Valence shell","Electron cloud","Inner shell"], answer: 1 },
    { question: "What type of chemical bond involves the transfer of electrons between atoms?", options: ["Covalent bond","Ionic bond","Hydrogen bond","Metallic bond"], answer: 1 },
    { question: "A molecule with two or more different elements chemically bonded together is called a:", options: ["Mixture","Solution","Compound","Element"], answer: 2 },
    { question: "What property of water means that its properties are not simply a combination of the properties of its elements?", options: ["Polarity","Hydrogen bonding","Emergent properties","Cohesion"], answer: 2 },
    { question: "Water is considered a polar molecule because oxygen is more ___________ than hydrogen.", options: ["Electronegative","Electropositive","Dense","Reactive"], answer: 0 },
    { question: "A weak attraction between two polar molecules is known as:", options: ["An ionic bond","A covalent bond","A hydrogen bond","A peptide bond"], answer: 2 },
    { question: "A substance that increases the concentration of hydrogen ions in water is defined as:", options: ["A base","A salt","A neutral solution","An acid"], answer: 3 },
    { question: "On the pH scale, a pH of 7 is considered:", options: ["Acidic","Basic","Neutral","Strong"], answer: 2 },
    { question: "The net movement of a substance from an area of high concentration to an area of low concentration is called:", options: ["Osmosis","Active transport","Diffusion","Endocytosis"], answer: 2 },
    { question: "The diffusion of water across a semi-permeable membrane is specifically called:", options: ["Diffusion","Active transport","Osmosis","Facilitated diffusion"], answer: 2 },
    { question: "Which of the following is NOT one of the four classes of biologically important macromolecules?", options: ["Lipids","Carbohydrates","Water","Proteins"], answer: 2 },
    { question: "Molecules that are non-polar and do not interact with water are described as:", options: ["Hydrophilic","Hydrophobic","Amphipathic","Polar"], answer: 1 },
    { question: "Proteins are polymers made up of smaller units called:", options: ["Monosaccharides","Nucleotides","Fatty acids","Amino acids"], answer: 3 },
    { question: "The specific sequence of amino acids in a protein is referred to as its:", options: ["Secondary structure","Tertiary structure","Primary structure","Quaternary structure"], answer: 2 },
    { question: "The functional unit of life is the:", options: ["Organ","Tissue","Cell","Molecule"], answer: 2 },
    { question: "Cells that lack a true nucleus are classified as:", options: ["Eukaryotic cells","Prokaryotic cells","Fungal cells","Plant cells"], answer: 1 },
    { question: "The gel-like fluid where many chemical reactions take place in a cell is called the:", options: ["Nucleus","Mitochondrion","Cytosol","Vacuole"], answer: 2 },
    { question: "The barrier around a cell that controls movement between the cell and its environment is the:", options: ["Cell wall","Plasma membrane","Capsule","Nucleoid"], answer: 1 },
    { question: "The main function of ribosomes is:", options: ["Lipid synthesis","ATP generation","Protein synthesis","DNA replication"], answer: 2 },
    { question: "The extra-chromosomal DNA found in some prokaryotic cells is called:", options: ["The nucleoid","A plasmid","A chromosome","An intron"], answer: 1 },
    { question: "Eukaryotic cells have membrane-bound structures within their cytoplasm called:", options: ["Nucleoids","Ribosomes","Organelles","Plasmids"], answer: 2 },
    { question: "Which organelle is involved in lipid synthesis and detoxification?", options: ["Rough endoplasmic reticulum","Smooth endoplasmic reticulum","Golgi apparatus","Lysosome"], answer: 1 },
    { question: "The organelle responsible for modifying and packaging proteins is the:", options: ["Mitochondrion","Endoplasmic reticulum","Nucleus","Golgi apparatus"], answer: 3 },
    { question: "The 'powerhouse' of the cell, responsible for generating ATP through cellular respiration, is the:", options: ["Chloroplast","Mitochondrion","Nucleolus","Ribosome"], answer: 1 },
    { question: "Which organelle contains digestive enzymes?", options: ["Vacuole","Golgi apparatus","Lysosome","Endoplasmic reticulum"], answer: 2 },
    { question: "Photosynthesis in plant cells takes place in the:", options: ["Mitochondria","Nucleus","Chloroplasts","Cytosol"], answer: 2 },
    { question: "The metabolic pathway that breaks down glucose into two molecules of pyruvate is called:", options: ["The citric acid cycle","Glycolysis","Oxidative phosphorylation","Fermentation"], answer: 1 },
    { question: "Glycolysis occurs in which part of the cell?", options: ["Mitochondrial matrix","Inner mitochondrial membrane","Cytosol","Nucleus"], answer: 2 },
    { question: "The citric acid cycle occurs in which part of the eukaryotic cell?", options: ["Cytosol","Inner mitochondrial membrane","Mitochondrial matrix","Nucleus"], answer: 2 },
    { question: "The process that uses a proton gradient to generate ATP is called:", options: ["Glycolysis","The citric acid cycle","Fermentation","Oxidative phosphorylation"], answer: 3 },
    { question: "In the absence of oxygen, cells can regenerate NAD+ through a process called:", options: ["Cellular respiration","Oxidative phosphorylation","The citric acid cycle","Fermentation"], answer: 3 },
    { question: "The light-dependent reactions of photosynthesis occur in the:", options: ["Stroma","Cytosol","Thylakoid membranes","Mitochondrial matrix"], answer: 2 },
    { question: "The Calvin cycle occurs in the ___________ of chloroplasts.", options: ["Thylakoid space","Inner membrane","Stroma","Outer membrane"], answer: 2 },
    { question: "The splitting of water molecules during the light reactions of photosynthesis produces:", options: ["CO2","ATP","NADPH","O2"], answer: 3 },
    { question: "Chlorophyll a absorbs light most strongly in which parts of the visible spectrum?", options: ["Green and yellow","Red and blue","Orange and yellow","Violet and green"], answer: 1 },
    { question: "The cell cycle phase during which DNA replication occurs is the:", options: ["G1 phase","S phase","G2 phase","M phase"], answer: 1 },
    { question: "The stage of mitosis characterized by chromosome condensation is:", options: ["Metaphase","Anaphase","Telophase","Prophase"], answer: 3 },
    { question: "The division of the cytoplasm during cell division is called:", options: ["Mitosis","Meiosis","Cytokinesis","Karyokinesis"], answer: 2 },
    { question: "In plant cell cytokinesis, a ___________ forms to divide the cytoplasm.", options: ["Cleavage furrow","Cell plate","Spindle fiber","Nuclear envelope"], answer: 1 },
    { question: "The process of cell division that produces two genetically identical daughter cells is:", options: ["Meiosis","Binary fission","Fertilization","Mitosis"], answer: 3 },
    { question: "A hypothesis that has been confirmed to such a degree that it would be perverse to withhold provisional consent is considered a:", options: ["Theory","Fact","Law","Principle"], answer: 1 },
    { question: "An enzyme is a protein that acts as a ___________ to make chemical reactions occur more easily.", options: ["Substrate","Product","Inhibitor","Catalyst"], answer: 3 },
    { question: "The movement of molecules in a given sample is measured by:", options: ["Pressure","Volume","Temperature","Density"], answer: 2 },
    { question: "Which type of protein is embedded in the phospholipid bilayer and allows certain molecules to pass through the membrane?", options: ["Receptor protein","Channel protein","Peripheral protein","Glycoprotein"], answer: 1 },
    { question: "The process where the plasma membrane of the cell engulfs particles and packages them in a vesicle to be released into the cytoplasm is called:", options: ["Exocytosis","Pinocytosis","Phagocytosis","Endocytosis"], answer: 3 },
    { question: "What are the little channels that connect the cytosol of one plant cell to the cytosol of an adjacent cell?", options: ["Cell wall","Middle lamella","Plasmodesmata","Pores"], answer: 2 },
    { question: "What is the main component of fungal cell walls?", options: ["Cellulose","Peptidoglycan","Chitin","Keratin"], answer: 2 },
    { question: "The primary function of ATP (adenosine triphosphate) in cells is to:", options: ["Store genetic information","Provide energy for cellular processes","Catalyze enzymatic reactions","Transport molecules across membranes"], answer: 1 },
    { question: "Cellular respiration is a set of metabolic pathways that convert chemical energy from nutrients into what molecule?", options: ["Glucose","Pyruvate","ATP","Oxygen"], answer: 2 },
    { question: "The process of photosynthesis uses light energy to synthesize carbohydrates out of which two molecules?", options: ["Oxygen and water","Carbon dioxide and oxygen","Glucose and oxygen","Carbon dioxide and water"], answer: 3 }
  ]
}; 