const courses = {
  aviation: [], // existing aviation code omitted for brevity
  biology: [
    { question: "Science relies on what to test natural explanations?", options: ["Speculative ideas","Observations","Beliefs","Authority"], answer: 1 },
    { question: "A hypothesis is best defined as:", options: ["A comprehensive explanation","A proven fact","A testable statement","A random guess"], answer: 2 },
    { question: "A scientific theory is:", options: ["A proven fact","An untested idea","A comprehensive explanation supported by evidence","A single experiment result"], answer: 2 },
    { question: "In science, evidence refers to:", options: ["Opinions of experts","Observations","Unvalidated claims","Popular belief"], answer: 1 },
    { question: "The scientific method requires:", options: ["Emotional reasoning","Testable predictions","Unquestioned assumptions","A single experiment"], answer: 1 },
    { question: "Fact in science is a hypothesis that has been:", options: ["Disproven","Ignored","Provisionally accepted","Randomly chosen"], answer: 2 },
    { question: "Theory differs from fact as it provides:", options: ["Experimental error","Explanatory power","Certainty","None of the above"], answer: 1 },
    { question: "Elements are substances that cannot be further broken down by chemical means.", options: ["True","False"], answer: 0 },
    { question: "Atomic number equals the number of protons in an atom.", options: ["True","False"], answer: 0 },
    { question: "Valence shell can hold up to how many electrons?", options: ["2","8","18","32"], answer: 1 },
    { question: "A covalent bond involves:", options: ["Transfer of electrons","Sharing of electrons","Complete loss of electrons","Magnetic attraction"], answer: 1 },
    { question: "An ionic bond involves:", options: ["Sharing of electrons","Transfer of electrons","No electron interaction","Electron tunneling"], answer: 1 },
    { question: "Water is polar because:", options: ["Hydrogen is more electronegative","Oxygen is more electronegative","It has no charge","It is nonpolar"], answer: 1 },
    { question: "pH 7 is considered:", options: ["Acidic","Neutral","Basic","Salt"], answer: 1 },
    { question: "Higher pH indicates lower hydrogen ion concentration.", options: ["True","False"], answer: 0 },
    { question: "Prokaryotes lack a true nucleus.", options: ["True","False"], answer: 0 },
    { question: "Prokaryotic ribosomes are:", options: ["Membrane-bound","Free-floating","Absent","Only in nucleus"], answer: 1 },
    { question: "Cell wall function is to:", options: ["Generate ATP","Provide shape and prevent bursting","Store DNA","Transmit signals"], answer: 1 },
    { question: "Flagella in bacteria:", options: ["Whip like eukaryotes","Rotate to provide motility","Are for photosynthesis","Are not present"], answer: 1 },
    { question: "Plasmids are:", options: ["Membrane proteins","Ribosomes","Extra-chromosomal DNA","Lipid droplets"], answer: 2 },
    { question: "Cytosol is the gel-like fluid where enzymes and molecules are suspended.", options: ["True","False"], answer: 0 },
    { question: "Eukaryotes have membrane-bound nucleus.", options: ["True","False"], answer: 0 },
    { question: "Rough ER synthesizes proteins for export.", options: ["True","False"], answer: 0 },
    { question: "Smooth ER is involved in lipid synthesis and detoxification.", options: ["True","False"], answer: 0 },
    { question: "Golgi apparatus modifies and packages proteins.", options: ["True","False"], answer: 0 },
    { question: "Mitochondria generate ATP.", options: ["True","False"], answer: 0 },
    { question: "Cytoskeleton gives cell shape and support.", options: ["True","False"], answer: 0 },
    { question: "Lysosome contains digestive enzymes.", options: ["True","False"], answer: 0 },
    { question: "Chloroplasts perform photosynthesis in plant cells.", options: ["True","False"], answer: 0 },
    { question: "Glycolysis breaks glucose into two pyruvates.", options: ["True","False"], answer: 0 },
    { question: "Glycolysis occurs in the cytosol.", options: ["True","False"], answer: 0 },
    { question: "Citric Acid Cycle occurs in the mitochondrial matrix.", options: ["True","False"], answer: 0 },
    { question: "Oxidative phosphorylation uses a proton gradient.", options: ["True","False"], answer: 0 },
    { question: "Each NADH yields approximately 2.5 ATP.", options: ["True","False"], answer: 0 },
    { question: "Fermentation regenerates NAD+ in absence of oxygen.", options: ["True","False"], answer: 0 },
    { question: "Light reactions occur in thylakoid membranes.", options: ["True","False"], answer: 0 },
    { question: "Calvin cycle occurs in the stroma.", options: ["True","False"], answer: 0 },
    { question: "Light reactions produce ATP and NADPH.", options: ["ATP only","NADPH only","ATP and NADPH","O2 only"], answer: 2 },
    { question: "Photolysis of water produces O2.", options: ["True","False"], answer: 0 },
    { question: "Chlorophyll a absorbs red and blue light most strongly.", options: ["True","False"], answer: 0 },
    { question: "Cyclic electron flow generates extra ATP.", options: ["True","False"], answer: 0 },
    { question: "Mitosis produces two genetically identical daughter cells.", options: ["True","False"], answer: 0 },
    { question: "DNA replication occurs during S phase.", options: ["True","False"], answer: 0 },
    { question: "Prophase involves chromosome condensation.", options: ["True","False"], answer: 0 },
    { question: "Cytokinesis divides the cytoplasm.", options: ["True","False"], answer: 0 },
    { question: "Plant cell cytokinesis forms a cell plate.", options: ["True","False"], answer: 0 }
  ]
}; 